# Generated by Django 3.2.19 on 2023-05-23 06:58

from django.db import migrations, models
import pet_stagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[pet_stagram.photos.validators.validate_image_less_than_5MB]),
        ),
    ]
